// ============================================================
// Demaze Intelligence Scorer — Deterministic Scoring Engine
// ============================================================
// Scores are NEVER generated by the LLM.
// The LLM extracts facts and sets boolean flags (DetectedFactors).
// This module converts those flags into deterministic numeric scores.
//
// Separation of concerns:
//   LLM  → evidence extraction, reasoning, narrative explanation
//   Code → score computation (this file)
// ============================================================

// ── Factor detection flags (LLM sets these, code reads them) ──

export interface DetectedFactors {
  growth_signal: boolean               // any growth signals found
  hiring_signal: boolean               // any hiring signals found
  digital_transformation: boolean      // digital transformation signals found
  capacity_expansion: boolean          // specifically: capacity expansion signal
  automation_keywords: boolean         // automation/robot/autonomous keywords in content
  technology_investment: boolean       // technology investment or CAPEX for tech
  ai_mention: boolean                  // explicit AI/ML/artificial intelligence mention
  multi_location_operations: boolean   // multiple plants, facilities, or locations
  industry_40_initiative: boolean      // Industry 4.0 / smart factory / IIoT program
  recent_news_or_event: boolean        // recent acquisition, expansion, funding, news
}

// ── Score output types ─────────────────────────────────────────

export interface ScoreBreakdownItem {
  factor: string   // human-readable factor name
  points: number   // max points for this factor
  present: boolean // whether the factor was detected
}

export interface ScoreWithBreakdown {
  value: number               // 0–100 final score (after confidence cap)
  label: 'Strong' | 'Good' | 'Moderate' | 'Weak'
  rationale?: string          // narrative from LLM (optional)
  breakdown: ScoreBreakdownItem[]
}

export interface ComputedScores {
  company_fit: ScoreWithBreakdown
  automation_opportunity: ScoreWithBreakdown
  outreach_priority: {
    value: number
    label: 'Strong' | 'Good' | 'Moderate' | 'Weak'
    rationale?: string
  }
  why_now: {
    score: number        // 0–10 (from LLM, capped by confidence)
    explanation: string  // narrative from LLM
    urgency_label: string
  }
}

// ── Weight tables ──────────────────────────────────────────────

// COMPANY FIT: how well does this company match Demaze's ICP?
// Max total = 100
const COMPANY_FIT_FACTORS: Array<{
  key: keyof DetectedFactors
  label: string
  points: number
}> = [
  { key: 'digital_transformation',    label: 'Digital Transformation Initiative',  points: 20 },
  { key: 'growth_signal',             label: 'Growth Signal Detected',              points: 15 },
  { key: 'capacity_expansion',        label: 'Capacity Expansion Underway',         points: 15 },
  { key: 'technology_investment',     label: 'Technology Investment',               points: 15 },
  { key: 'industry_40_initiative',    label: 'Industry 4.0 / Smart Factory',        points: 10 },
  { key: 'multi_location_operations', label: 'Multi-location Operations',           points: 10 },
  { key: 'hiring_signal',             label: 'Active Hiring / Growth Momentum',     points: 10 },
  { key: 'recent_news_or_event',      label: 'Recent Business Event',               points: 5  },
]
// Total possible: 100

// AUTOMATION OPPORTUNITY: how much AI/automation potential exists?
// Max total = 100
const AUTOMATION_OPP_FACTORS: Array<{
  key: keyof DetectedFactors
  label: string
  points: number
}> = [
  { key: 'ai_mention',                label: 'AI / ML Mentioned in Content',        points: 25 },
  { key: 'digital_transformation',    label: 'Active Digital Transformation',       points: 20 },
  { key: 'automation_keywords',       label: 'Automation Keywords in Content',      points: 20 },
  { key: 'industry_40_initiative',    label: 'Industry 4.0 Initiative Active',      points: 15 },
  { key: 'technology_investment',     label: 'Technology Investment Confirmed',     points: 15 },
  { key: 'hiring_signal',             label: 'Technical Hiring Underway',           points: 5  },
]
// Total possible: 100

// ── Score caps by content confidence ──────────────────────────
// Thin content cannot justify high scores regardless of signals.
const SCORE_CAPS: Record<string, number> = {
  high:   100,
  medium:  82,  // prevents LLM over-enthusiasm on partial data
  low:     50,  // honest — we don't know enough
}

// ── Helpers ────────────────────────────────────────────────────

function cap(value: number, confidence: string): number {
  return Math.min(value, SCORE_CAPS[confidence] ?? 100)
}

function scoreLabel(value: number): 'Strong' | 'Good' | 'Moderate' | 'Weak' {
  if (value >= 80) return 'Strong'
  if (value >= 60) return 'Good'
  if (value >= 40) return 'Moderate'
  return 'Weak'
}

function urgencyLabel(score: number): string {
  if (score >= 8) return 'Contact immediately'
  if (score >= 5) return 'Contact this week'
  if (score >= 2) return 'Watch list'
  return 'Deprioritize'
}

// ── Main export ────────────────────────────────────────────────

/**
 * Compute all scores deterministically from LLM-extracted boolean flags.
 *
 * @param factors     DetectedFactors from LLM (booleans for each signal type)
 * @param whyNowScore 0–10 urgency score — the ONLY numeric score the LLM provides
 * @param confidence  'high' | 'medium' | 'low' — caps all scores
 * @param whyNowExplanation  LLM narrative for why now
 * @param fitExplanation     LLM narrative for company fit
 * @param oppExplanation     LLM narrative for automation opportunity
 * @param priorityExplanation LLM narrative for outreach priority
 */
export function computeScores(
  factors: Partial<DetectedFactors>,
  whyNowScore: number,
  confidence: string,
  whyNowExplanation: string,
  fitExplanation?: string,
  oppExplanation?: string,
  priorityExplanation?: string,
): ComputedScores {
  const f = (factors ?? {}) as DetectedFactors

  // Cap why_now_score for low confidence
  const whyNowCapped = confidence === 'low'
    ? Math.min(whyNowScore, 5)
    : Math.max(0, Math.min(whyNowScore, 10))

  // ── Company Fit ─────────────────────────────────────────────
  const fitBreakdown: ScoreBreakdownItem[] = COMPANY_FIT_FACTORS.map(item => ({
    factor: item.label,
    points: item.points,
    present: Boolean(f[item.key]),
  }))
  const fitRaw = fitBreakdown
    .filter(b => b.present)
    .reduce((sum, b) => sum + b.points, 0)
  const fitValue = cap(Math.min(fitRaw, 100), confidence)

  // ── Automation Opportunity ──────────────────────────────────
  const oppBreakdown: ScoreBreakdownItem[] = AUTOMATION_OPP_FACTORS.map(item => ({
    factor: item.label,
    points: item.points,
    present: Boolean(f[item.key]),
  }))
  const oppRaw = oppBreakdown
    .filter(b => b.present)
    .reduce((sum, b) => sum + b.points, 0)
  const oppValue = cap(Math.min(oppRaw, 100), confidence)

  // ── Outreach Priority ───────────────────────────────────────
  // Weighted combo: fit contributes 35%, opportunity 30%, urgency 35%
  const priorityRaw =
    (fitValue * 0.35) +
    (oppValue * 0.30) +
    (whyNowCapped * 10 * 0.35)
  const priorityValue = cap(Math.round(priorityRaw), confidence)

  return {
    company_fit: {
      value: fitValue,
      label: scoreLabel(fitValue),
      rationale: fitExplanation,
      breakdown: fitBreakdown,
    },
    automation_opportunity: {
      value: oppValue,
      label: scoreLabel(oppValue),
      rationale: oppExplanation,
      breakdown: oppBreakdown,
    },
    outreach_priority: {
      value: priorityValue,
      label: scoreLabel(priorityValue),
      rationale: priorityExplanation,
    },
    why_now: {
      score: whyNowCapped,
      explanation: whyNowExplanation,
      urgency_label: urgencyLabel(whyNowCapped),
    },
  }
}

// ── Cluster-based opportunity floor ───────────────────────────
//
// AUTOMATION_OPP_FACTORS are manufacturing-keyword-based.
// For conglomerates, SaaS, and engineering companies those keywords
// don't appear → scores stuck at 20–30 even when multiple high-tier
// opportunity clusters exist.
//
// This function computes a floor: if strong signal clusters are present,
// automation_opportunity cannot be below this floor.

const CLUSTER_OPPORTUNITY_FLOOR: Record<string, number> = {
  manufacturing_intelligence:             30,
  industrial_ai:                          30,
  saas_customer_operations:               35,
  conglomerate_enterprise_intelligence:   35,
  engineering_delivery_intelligence:      25,
  multi_site_coordination:                20,
  scale_and_capacity:                     15,
  technology_integration:                 15,
  dealer_distribution_network:            20,
  automotive_after_sales:                 20,
  saas_product_intelligence:              25,
  workforce_intelligence:                 10,
  supply_chain_growth:                    10,
  business_event_momentum:                 5,
}

export function computeClusterOpportunityFloor(
  clusters: Array<{ id: string; confidence: string; tier: number }>,
): number {
  let total = 0
  for (const cluster of clusters) {
    const base = CLUSTER_OPPORTUNITY_FLOOR[cluster.id] ?? 0
    let multiplier = 0.5
    if (cluster.confidence === 'high')   multiplier = 1.0
    else if (cluster.confidence === 'medium') multiplier = 0.75
    total += base * multiplier
  }
  return Math.min(Math.round(total), 88)
}

// Re-export scoreLabel for use in normalize.ts
export { scoreLabel }
